import Config

config :topics_club_core, TopicsClub.Vault,
  ciphers: [
    default:
      {Cloak.Ciphers.AES.GCM,
       tag: "AES.GCM.V1",
       key: Base.decode64!("fRmXbEDcBN/ho4mJzfvUJh4aYwNKbBd32vqJ0b2w3YI="),
       iv_length: 12}
  ]

# Configure your database
config :topics_club_core, TopicsClub.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "topics_club_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :topics_club_gateway, TopicsClubWeb.Endpoint,
  http: [ip: {0, 0, 0, 0}, port: 4100],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "3ps+1yKVI13aG3co2FGgVxg8XdNe1gIorL/WOix/XizngsGbDm67jXVQpDbxgbsr",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:topics_club, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:topics_club, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :topics_club_gateway, TopicsClubWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"apps/topics_club_gateway/priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"apps/topics_club_gateway/priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"apps/topics_club_gateway/lib/topics_club_web/router\.ex$"E,
      ~r"apps/topics_club_gateway/lib/topics_club_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :topics_club_gateway, dev_routes: true

# Keep development logs compact while retaining searchable operational metadata.
config :logger, :default_formatter, format: "[$level] $metadata$message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
